### ISSUE TITLE
PMK 7 TODO

### ISSUE THREAD

**Issue by mxcl** [mxcl/PromiseKit#898]
- [ ] `conf.Q` should be closures rather than taking values of queues, since `.global()` usually returns different queues, and otherwise PMK with `map` with a value of a queue will only ever use the same queue.
- [ ] `CLLocationManager.requestLocation()` should be an instance method so you can configure its parameters.
- [ ] Attempt to rename all PromiseKit org repos with a `PMK` prefix (because Carthage only has one level of namespace)
- [ ] Standardize versions in PromiseKit org to v7 (they should stay in sync since we can't break binary compatibility in CocoaPods without doing the same in the extensions the pod contains)
- [ ] It’s `MessageUI` not `MessagesUI` for that extension
- [ ] If we can default the extensions to be static libs for CocoaPods with PMK7 we can make them separate pods which would be better (?)
- [ ] Disambiguate `recover` usage more.
- [ ] Provide a `catch` variant (named else-wise for disambiguity?) that allows catching only specific types of error (if possible)
- [ ] `finally` variant that can return a `Guarantee` like `ensureThen`
- [ ] Include convenience function `thenAnimate` for UIKit extension
- [ ] Provide `when(resolved:concurrently:)`
- [ ] `when(concurrently:)` should take closure that can throw instead of an iterator
- [ ] Default catch policy to all errors, document how to undo this in migration guide, and in regular documentation. Has advantages, it's just people get confused so make opt-in.
- [ ] No more submodules for extensions, therefore no more subspecs, it makes cloning PromiseKit take ages and means our semantic version is not always correct, also makes major version bumps for extensions impossible. Instead have pod `PMKFoundation` etc.
- [ ] Restore https://github.com/mxcl/PromiseKit/issues/990
- [ ] Renames as detailed in: https://github.com/PromiseKit/CoreLocation/pull/25

**Comment by GarthSnyder** [comment]
I can address this since I'm touching this stuff anyway. However, I'm afraid I don't understand the issue. Can you clarify?

**Comment by mxcl** [comment]
I'm not sure it's actually true, I did some testing and `.global()` maybe does always return the same queue. Not sure.

Either way rather than have the variable be `: DispatchQueue` the ticket is for it to be `: () -> DispatchQueue`

**Comment by mxcl** [comment]
Closing as all are basically not needed or not important.
